#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgreq -x picom > /dev/null || picom &
pgreq -x cinnamon-session > /dev/null || cinnamon-session &
pgreq -x polybar > /dev/null || polybar &

bspc monitor -d 󰇩 󰨞 󰨞 󰨞 󰨞  󰓇  󰍻

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Cinnamon-settings.py state=floating
bspc rule -a "cinnamon-settings network" state=floating
bspc rule -a zen-alpha desktop='^1'
bspc rule -a Spotify desktop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a Code desktop='^2'

# Run flatpak package
flatpak run com.spotify.Client &


