#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgreq -x picom > /dev/null || picom &
pgreq -x cinnamon-session > /dev/null || cinnamon-session &
pgreq -x polybar > /dev/null || polybar &

bspc monitor -d 󰇩 󰨞 󰨞 󰨞 󰨞  󰓇  󰍻

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Edge desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


