# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15


#[spotify-pwa]
#command=var=$(xdotool search --classname crx__pjibgclleladliembfgfagdaldikeohf)&&xdotool getwindowname $var 2>/dev/null | cut -c -32
#interval=5i

[time]
command=date '+  %m/%d  %H:%M '
interval=1i


